name: node
version: v26.10.0
source:
  url: https://nodejs.org/dist/{version}/SHASUMS256.txt
assets:
  linux-amd64-gnu:
    file: node-{version}-linux-x64.tar.xz
    format: tar.xz
    checksum: SHASUMS256.txt
    url: https://nodejs.org/dist/{version}/node-{version}-linux-x64.tar.xz
  linux-arm64-gnu:
    file: node-{version}-linux-arm64.tar.xz
    format: tar.xz
    checksum: SHASUMS256.txt
    url: https://nodejs.org/dist/{version}/node-{version}-linux-arm64.tar.xz
  linux-amd64-musl:
    file: node-{version}-linux-x64.tar.xz
    format: tar.xz
    checksum: SHASUMS256.txt
    url: https://nodejs.org/dist/{version}/node-{version}-linux-x64.tar.xz
  linux-arm64-musl:
    file: node-{version}-linux-arm64.tar.xz
    format: tar.xz
    checksum: SHASUMS256.txt
    url: https://nodejs.org/dist/{version}/node-{version}-linux-arm64.tar.xz
  darwin-amd64:
    file: node-{version}-darwin-x64.tar.gz
    format: tar.gz
    checksum: SHASUMS256.txt
    url: https://nodejs.org/dist/{version}/node-{version}-darwin-x64.tar.gz
  darwin-arm64:
    file: node-{version}-darwin-arm64.tar.gz
    format: tar.gz
    checksum: SHASUMS256.txt
    url: https://nodejs.org/dist/{version}/node-{version}-darwin-arm64.tar.gz
  windows-amd64:
    file: node-{version}-win-x64.zip
    format: zip
    checksum: SHASUMS256.txt
    url: https://nodejs.org/dist/{version}/node-{version}-win-x64.zip
  windows-arm64:
    file: node-{version}-win-arm64.zip
    format: zip
    checksum: SHASUMS256.txt
    url: https://nodejs.org/dist/{version}/node-{version}-win-arm64.zip
executables:
  - node